
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-03
owner: ucsb-cs156-s26
repo_name: team02-s26-03
pull_requests: [{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu_33","number":102,"title":"Add MenuItemReview placeholder pages, routes, and navbar link.","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/102"},{"author":{"id":"MDQ6VXNlcjM5MDM1Njg0","is_bot":false,"login":"kalyanrajavaram","name":""},"headRefName":"kx-fix-indexpage-url","number":101,"title":"Fix URL casing in edit/create pages and their tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/101"}]
