
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-03
owner: ucsb-cs156-s26
repo_name: team02-s26-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwMzkwOTg2","is_bot":false,"login":"applebee1558","name":"Alex Liu"},"headRefName":"add-integrationtest-applebee1558","number":113,"title":"add articles integration test","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/113"},{"author":{"id":"MDQ6VXNlcjUzOTgxMDM3","is_bot":false,"login":"Hrithik-M","name":""},"headRefName":"hrithik-team03-end-tests","number":110,"title":"RecommendationRequest end to end tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/110"},{"author":{"id":"MDQ6VXNlcjUzOTgxMDM3","is_bot":false,"login":"Hrithik-M","name":""},"headRefName":"hrithik-team03-tests","number":109,"title":"RecommendationRequests Integration tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/109"}]
