
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-03
owner: ucsb-cs156-s26
repo_name: team02-s26-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMzU2Mzg0","is_bot":false,"login":"POWERTRICEPS","name":"Raymond Xie"},"headRefName":"rx-org-e2e","number":123,"title":"Add UCSBOrganization end-to-end tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/123"},{"author":{"id":"MDQ6VXNlcjUzMzU2Mzg0","is_bot":false,"login":"POWERTRICEPS","name":"Raymond Xie"},"headRefName":"rx-org-test","number":122,"title":"Add UCSBOrganization integration tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/122"},{"author":{"id":"MDQ6VXNlcjMwMzkwOTg2","is_bot":false,"login":"applebee1558","name":"Alex Liu"},"headRefName":"add-articlese2etest-applebee1558","number":114,"title":"Add articlese2etest applebee1558","url":"https://github.com/ucsb-cs156-s26/team02-s26-03/pull/114"}]
